# Generated by Django 3.1.8 on 2021-05-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='calendars.Item')),
            ],
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
        migrations.AddField(
            model_name='calendar',
            name='dates',
            field=models.ManyToManyField(to='calendars.Date'),
        ),
    ]
