# Generated by Django 3.1.8 on 2021-05-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_auto_20210527_1506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Event',
        ),
        migrations.RemoveField(
            model_name='date',
            name='items',
        ),
        migrations.AddField(
            model_name='date',
            name='event',
            field=models.ManyToManyField(to='calendars.Event'),
        ),
    ]
