# Generated by Django 3.1.8 on 2021-05-28 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='calendars.user'),
            preserve_default=False,
        ),
    ]
