# Generated by Django 3.1.8 on 2021-06-01 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0007_calendar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calendar',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='calendars.calendar'),
        ),
    ]
