# Generated by Django 3.1.8 on 2021-06-02 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0008_userprofile_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='event',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='calendar',
        ),
        migrations.AddField(
            model_name='date',
            name='summary',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calendars.userprofile'),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calendars.date'),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calendars.userprofile'),
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
