# Generated by Django 3.1.8 on 2021-06-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0010_auto_20210602_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default=None, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='date',
            field=models.DateField(blank=True, default=None, editable=False),
        ),
    ]
