# Generated by Django 3.1.8 on 2021-06-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0012_auto_20210602_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
